[package]
name = "oma"
version = "1.7.1"
edition = "2021"
description = "User-friendly and performant package manager for APT repositories"
license = "GPL-3.0-or-later"
authors = ["eatradish <sakiiily@aosc.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Cli
clap = { version = "4.5.16", features = ["cargo", "wrap_help", "color", "string"] }
anyhow = "1.0.86"
ctrlc = "3.4.5"
tabled = { version = "0.16.0", features = ["ansi"] }
dialoguer = "0.11.0"
tokio = "1.39.3"
derive_builder = "0.20.0"
oma-inquire = "0.1.1"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
toml = "0.8.19"
dashmap = "6.0.1"
chrono = "0.4.38"
rustix = { version = "0.38.34", features = ["process"] }
colored = { version = "2.1.0", optional = true }
image = { version = "0.25.2", optional = true }
libc = "0.2.158"
reqwest = { version = "0.12.7", default-features = false }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
smallvec = "1.13.2"
console-subscriber = { version = "0.4.0", optional = true }
ratatui = "=0.26.0"
crossterm = "0.28.1"
ansi-to-tui = "4.1.0"
glob-match = "0.2.1"
which = "6.0.3"
strsim = "0.11.1"
ahash = "0.8.11"

# oma crates
oma-utils = { path = "./oma-utils", features = ["dbus", "human-bytes", "oma"] }
oma-console = { path = "./oma-console" }
oma-pm = { path = "./oma-pm" }
oma-refresh = { path = "./oma-refresh", default-features = false }
oma-contents = { path = "./oma-contents" }
oma-fetch = { path = "./oma-fetch", default-features = false }
oma-topics = { path = "./oma-topics", optional = true, default-features = false }
oma-history = { path = "./oma-history" }
oma-repo-verify = { path = "./oma-repo-verify" }

# i18n
i18n-embed = { version = "0.15.0", features = ["fluent-system", "desktop-requester"]}
i18n-embed-fl = "0.9.1"
rust-embed = "8.5.0"
unic-langid = "0.9.5"
indexmap = "2.4.0"

[build-dependencies]
clap_mangen = "0.2.23"
clap_complete = "4.5.20"
clap = { version = "4.5.16", features = ["cargo", "wrap_help", "color", "string"] }
anyhow = "1.0.86"

[features]
aosc = ["dep:oma-topics", "oma-refresh/aosc", "oma-pm/aosc", "oma-contents/aosc"]
sequoia-openssl-backend = ["oma-refresh/sequoia-openssl-backend"]
sequoia-nettle-backend = ["oma-refresh/sequoia-nettle-backend"]
egg = ["dep:colored", "dep:image"]
tokio-console = ["dep:console-subscriber"]
rustls = ["reqwest/rustls-tls", "oma-fetch/rustls", "oma-refresh/rustls", "oma-topics/rustls"]
openssl = ["reqwest/native-tls", "oma-fetch/native-tls", "oma-refresh/native-tls", "oma-topics/native-tls"]
generic = ["sequoia-nettle-backend", "rustls"]
default = ["aosc", "generic"]

[workspace]
members = ["oma-contents", "oma-console", "oma-topics", "oma-fetch", "oma-refresh", "oma-utils", "oma-pm", "oma-history", "oma-pm-operation-type", "oma-repo-verify"]

[package.metadata.deb]
copyright = "2024, AOSC Dev <maintainers@aosc.io>"
maintainer = "eatradish <sakiiily@aosc.io>"
license-file = ["COPYING", "4"]
extended-description = "User-friendly and performant package manager for APT repositories"
depends = "$auto"
section = "admin"
priority = "optional"
assets = [
    ["target/release/oma", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/oma/README", "644"],
    ["data/config/oma.toml", "etc/oma.toml", "755"],
    ["data/dbus/oma-dbus.conf", "usr/share/dbus-1/oma-dbus.conf", "755"]
]
features = ["generic"]
default-features = false

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
