[package]
name = "oma"
version = "1.6.0"
edition = "2021"
description = "User-friendly and performant package manager for APT repositories"
license = "GPL-3.0-or-later"
authors = ["eatradish <sakiiily@aosc.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Cli
clap = { version = "4.2.4", features = ["cargo", "wrap_help", "color", "string"] }
anyhow = "1.0"
ctrlc = "3.4"
tabled = { version = "0.16", features = ["ansi"] }
dialoguer = "0.11"
tokio = "1.34"
derive_builder = "0.20.0"
oma-inquire = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
dashmap = "6.0"
chrono = "0.4"
rustix = { version = "0.38.31", features = ["process"] }
colored = { version = "2.0.4", optional = true }
image = { version = "0.25", optional = true }
libc = "0.2"
reqwest = { version = "0.12", default-features = false }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
smallvec = "1.11"
console-subscriber = { version = "0.4", optional = true }
ratatui = "=0.26"
crossterm = "0.28"
ansi-to-tui = "4.0"
glob-match = "0.2"

# oma crates
oma-utils = { path = "./oma-utils", features = ["dbus", "human-bytes", "oma"] }
oma-console = { path = "./oma-console" }
oma-pm = { path = "./oma-pm" }
oma-refresh = { path = "./oma-refresh", default-features = false }
oma-contents = { path = "./oma-contents" }
oma-fetch = { path = "./oma-fetch", default-features = false }
oma-topics = { path = "./oma-topics", optional = true, default-features = false }
oma-history = { path = "./oma-history" }
oma-repo-verify = { path = "./oma-repo-verify" }

# i18n
i18n-embed = { version = "0.15", features = ["fluent-system", "desktop-requester"]}
i18n-embed-fl = "0.9"
rust-embed = "^8"
unic-langid = "0.9"

[build-dependencies]
clap_mangen = "0.2.10"
clap_complete = "4.2"
clap = { version = "4.3", features = ["cargo", "wrap_help", "color", "string"] }
anyhow = "1.0.75"

[features]
aosc = ["dep:oma-topics", "oma-refresh/aosc", "oma-pm/aosc"]
contents-without-rg = ["oma-contents/no-rg-binary"]
sequoia-openssl-backend = ["oma-refresh/sequoia-openssl-backend"]
sequoia-nettle-backend = ["oma-refresh/sequoia-nettle-backend"]
egg = ["dep:colored", "dep:image"]
tokio-console = ["dep:console-subscriber"]
rustls = ["reqwest/rustls-tls", "oma-fetch/rustls", "oma-refresh/rustls", "oma-topics/rustls"]
openssl = ["reqwest/native-tls", "oma-fetch/native-tls", "oma-refresh/native-tls", "oma-topics/native-tls"]
generic = ["sequoia-nettle-backend", "rustls"]
default = ["aosc", "generic"]

[workspace]
members = ["oma-contents", "oma-console", "oma-topics", "oma-fetch", "oma-refresh", "oma-utils", "oma-pm", "oma-history", "oma-pm-operation-type", "oma-repo-verify"]

[package.metadata.deb]
copyright = "2024, AOSC Dev <maintainers@aosc.io>"
maintainer = "eatradish <sakiiily@aosc.io>"
license-file = ["COPYING", "4"]
extended-description = "User-friendly and performant package manager for APT repositories"
depends = "$auto"
section = "admin"
priority = "optional"
assets = [
    ["target/release/oma", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/oma/README", "644"],
    ["data/config/oma.toml", "etc/oma.toml", "755"],
    ["data/dbus/oma-dbus.conf", "usr/share/dbus-1/oma-dbus.conf", "755"]
]
features = ["generic"]
default-features = false
