[package]
name = "oma"
version = "1.2.0-alpha.0"
edition = "2021"
description = "Omakase (oma) - Package management interface for AOSC OS"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Cli
clap = { version = "4.2.4", features = ["cargo", "wrap_help", "color", "string"] }
once_cell = "1.18"
anyhow = "1.0"
ctrlc = "3.4"
tabled = { version = "0.14", features = ["color"] }
dialoguer = "0.11"
tokio = "1.15"
derive_builder = "0.12.0"
oma-inquire = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
rusqlite = { version = "0.29", features = ["bundled"] }
dashmap = "5.5"
chrono = "0.4"
rustix = { version = "0.38", features = ["process"] }
colored = { version = "2.0.4", optional = true }
image = { version = "0.24.7", optional = true }

# oma crates
oma-utils = { path = "./oma-utils", features = ["dbus", "human-bytes", "oma"] }
oma-console = { path = "./oma-console" }
oma-pm = { path = "./oma-pm" }
oma-refresh = { path = "./oma-refresh", default_features = false }
oma-contents = { path = "./oma-contents" }
oma-fetch = { path = "./oma-fetch" }
oma-topics = { path = "./oma-topics", optional = true }

# i18n
i18n-embed = { version = "0.14", features = ["fluent-system", "desktop-requester"]}
i18n-embed-fl = "0.7"
rust-embed = "^8"
unic-langid = "0.9"

[build-dependencies]
clap_mangen = "0.2.10"
clap_complete = "4.2"
clap = { version = "4.3", features = ["cargo", "wrap_help", "color", "string"] }
anyhow = "1.0.75"

[features]
aosc = ["dep:oma-topics", "oma-refresh/aosc"]
contents-without-rg = ["oma-contents/no-rg-binary"]
sequoia-openssl-backend = ["oma-refresh/sequoia-openssl-backend"]
sequoia-nettle-backend = ["oma-refresh/sequoia-nettle-backend"]
egg = ["dep:colored", "dep:image"]
default = ["aosc","sequoia-nettle-backend", "egg"]

[workspace]
members = ["oma-contents", "oma-console", "oma-topics", "oma-fetch", "oma-refresh", "oma-utils", "oma-pm"]
