[package]
name = "oma-history"
version = "0.1.0"
edition = "2021"
description = "A crate to help oma operate history database"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oma-pm = { version = "^0.13", path = "../oma-pm" }
rusqlite = { version = "0.29", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
thiserror = "1.0"
