[package]
name = "oma-topics"
version = "0.5.1"
edition = "2021"
description = "A crate to handle AOSC OS topics."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18"
indexmap = {version = "2.0", features = ["serde"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.28", default_features = false, features = ["fs"] }
thiserror = "1.0"
futures = "0.3"
oma-console = { version = "^0.7", path = "../oma-console" }

[dev-dependencies]
oma-inquire = "0.1"
oma-console = { path = "../oma-console" }
tokio = { version = "1.28", default_features = false, features = ["macros", "rt-multi-thread"] }
