[package]
name = "oma-pm"
version = "0.27.2"
edition = "2021"
description = "APT package manager API abstraction library"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oma-apt = "0.7"
thiserror = "1.0"
chrono = { version = "0.4", features = ["unstable-locales"] }
glob-match = "0.2"
indicium = "0.6"
oma-utils = { version = "^0.8.0", path = "../oma-utils", features = [
    "dpkg",
    "url-no-escape",
    "human-bytes",
] }
oma-fetch = { version = "^0.12.0", path = "../oma-fetch" }
tokio = { version = "1.15", default-features = false, features = [
    "fs",
    "rt-multi-thread",
] }
oma-console = { version = "^0.13.0", path = "../oma-console", default-features = false, features = [
    "print",
] }
derive_builder = "0.20"
fs4 = "0.9"
tracing = "0.1"
small-map = "0.1"
oma-pm-operation-type = { version = "0.2", path = "../oma-pm-operation-type" }
zbus = { version = "4.1", features = ["tokio"] }
cxx = "1.0.121"

[dev-dependencies]
dashmap = "6"
indicatif = "0.17"
oma-console = { version = "^0.13.0", path = "../oma-console", default-features = false, features = ["progress_bar_style"] }

[features]
aosc = []
