[package]
name = "oma-pm"
version = "0.15.3"
edition = "2021"
description = "A crate to help oma handle package manager operation"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oma-apt = "0.1"
thiserror = "1.0"
chrono = { version = "0.4", features = ["unstable-locales"] }
glob-match = "0.2"
indicium = "0.6"
oma-utils = { version = "^0.6.0", path = "../oma-utils", features = [
    "dpkg",
    "url-no-escape",
] }
oma-fetch = { version = "^0.8.0", path = "../oma-fetch" }
tokio = { version = "1.15", default_features = false, features = [
    "fs",
    "rt-multi-thread",
] }
oma-console = { version = "^0.9.0", path = "../oma-console", default-features = false, features = ["print"] }
derive_builder = "0.12"
fs4 = "0.7"
tracing = "0.1"
small-map = "0.1"
oma-pm-operation-type = { version = "0.1", path = "../oma-pm-operation-type" }

[dev-dependencies]
dashmap = "5.5"
indicatif = "0.17"
