[package]
name = "oma-utils"
version = "0.6.0"
edition = "2021"
description = "Some small-tools to help oma handle something"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
number_prefix = { version = "0.4", optional = true }
once_cell = "1.18"
os-release = "0.1"
oma-console = { version = "^0.9", path = "../oma-console", optional = true, default-features = false, features = [
    "print",
] }
zbus = { version = "3.14", optional = true }
url-escape = { version = "0.1", optional = true }
tracing = "0.1"

[features]
dpkg = []
human-bytes = ["number_prefix"]
dbus = ["zbus"]
oma = ["dep:oma-console"]
url-no-escape = ["url-escape"]
