[package]
name = "oma-contents"
version = "0.8.0"
edition = "2021"
description = "APT Contents metadata handling library"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.8"
chrono = "0.4"
thiserror = "1.0"
winnow = "0.6"
flate2 = "1.0"
rayon = "1.8"
lzzzz = "1.0"
tracing = "0.1"
which = "6"
zstd = "0.13"

[dev-dependencies]
indicatif = "0.17"
oma-utils = { path = "../oma-utils", features = ["dpkg"] }

[features]
aosc = []
