[package]
name = "apt-auth-config"
version = "0.2.0"
edition = "2021"
description = "Library to parse APT auth.conf.d configurations"
license = "MIT"

[dependencies]
thiserror = "2"
tracing = "0.1"
winnow = { version = "0.6.20" }
