[package]
name = "oma-refresh"
version = "0.9.1"
edition = "2021"
description = "A crate to help oma refresh apt repo database"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oma-fetch = { version = "^0.7.0", path = "../oma-fetch" }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
url = "2.3"
tokio = { version = "1.28", default_features = false, features = ["fs"] }
serde_yaml = "0.9"
once_cell = "1.18"
futures = "0.3"
oma-apt-sources-lists = "0.2"
oma-debcontrol = "0.3"
sequoia-openpgp = { version = "1.13", default_features = false }
anyhow = "1.0"
chrono = { version = "0.4", features = ["unstable-locales"] }
oma-topics = { version = "^0.5.0", path = "../oma-topics", optional = true }
reqwest = "0.11"
oma-utils = { version = "^0.2.0", path = "../oma-utils", features = ["dpkg"] }
oma-console = { version = "^0.7.0", path = "../oma-console" }
derive_builder = "0.12"

[features]
aosc = ["dep:oma-topics"]
sequoia-openssl-backend = ["sequoia-openpgp/crypto-openssl"]
sequoia-nettle-backend = ["sequoia-openpgp/crypto-nettle"]
default = ["aosc", "sequoia-nettle-backend"]

[dev-dependencies]
tokio = { version = "1.28", default_features = false, features = ["macros", "rt-multi-thread"] }
indicatif = "0.17"
dashmap = "5.5"
