[package]
name = "oma-console"
version = "0.9.0"
edition = "2021"
description = "Omakase (oma) console tools to help oma handle console"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = { version = "0.15", optional = true }
indicatif = { version = "0.17", optional = true }
once_cell = { version = "1.18", optional = true }
icu_segmenter = { version = "1.3", optional = true }
tracing = { version = "0.1", optional = true }
tracing-subscriber =  { version = "0.3", optional = true }

[features]
print = ["dep:tracing", "dep:tracing-subscriber", "dep:icu_segmenter", "dep:console", "dep:once_cell"]
pager = []
progress_bar_style = ["dep:indicatif"]
default = ["print", "pager", "progress_bar_style"]
