[package]
name = "oma-console"
version = "0.7.2"
edition = "2021"
description = "Omakase (oma) console tools to help oma handle console"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15"
indicatif = "0.17"
once_cell = "1.18"
icu_segmenter = "1.3"
