[package]
name = "oma-pm-operation-type"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.12"
serde = { version = "1.0", features = ["derive"] }
oma-utils = { version = "^0.5.0", path = "../oma-utils", features = [
    "human-bytes",
] }
