[package]
name = "oma-fetch"
version = "0.7.1"
edition = "2021"
description = "A downloader to help oma download something"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
reqwest = "0.11"
tokio = { version = "1.28", default_features = false, features = ["fs"] }
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"
sha2 = "0.10"
futures = "0.3"
oma-console = { version = "^0.7", path = "../oma-console" }
derive_builder = "0.12"
async-compression = { version = "0.4", features = ["tokio", "gzip", "xz"] }
oma-utils = { version = "^0.2", features = ["url-no-escape"] }

[dev-dependencies]
tokio = { version = "1.28", default-features = false, features = ["macros", "rt-multi-thread"] }
indicatif = "0.17"
dashmap = "5.5"
