name: Publish Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build-for-debian/ubuntu
        run: |
          cargo build —release —no-default-features —features generic
          cp target/release/oma target/release/oma-for-debian-ubuntu
      - name: Build-for-AOSCOS
        run: cargo build --release
      - name: Generate a release body
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header --no-exec --github-repo ${{ github.repository }}
        env:
          OUTPUT: CHANGELOG.md
      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/oma-for-debian-ubuntu
            target/release/oma
            data/config/oma.toml
          body: ${{ steps.git-cliff.outputs.content }}

